[package]
edition = "2021"
name = "ai-client"
version = "0.1.0"

[dependencies]
reqwest = {version = "0.12", features = ["json", "rustls-tls"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "3"
thiserror = "1"
# tokio = {version = "1", features = ["full"]}
